---
# The directory to store the kube certificates and other configuration
kube_conf_dir: "/var/lib/kubernetes"
# CNI network plugin settings
kube_cni_conf_dir: "/etc/cni/net.d"
# The directory from where to copy the kube certificates. By default this
# will expand to user's LOCAL $HOME (the user that run's "ansible-playbook ..."
# plus "/kube/certs". That means if the user's $HOME directory is e.g.
# "/home/da_user" then "kube_ca_conf_directory" will have a value of
# "/home/da_user/kube/certs".
kube_ca_conf_directory: "{{ '~/kube/certs' | expanduser }}"

etcd_conf_dir: "/etc/etcd"
etcd_bin_dir: "/usr/local/bin"
etcd_client_port: 2379

flannel_version: "v0.9.1"
flannel_etcd_prefix: "/kubernetes-cluster/network"
flannel_ip_range: "10.200.0.0/16"
flannel_backend_type: "host-gw"
flannel_cni_name: "podnet"
flannel_subnet_file_dir: "/run/flannel"
flannel_options_dir: "/etc/flannel"
flannel_bin_dir: "/usr/local/sbin"
flannel_ip_masq: "true"
flannel_cni_conf_file: "10-flannel"
flannel_healthz_ip: "0.0.0.0"
flannel_healthz_port: "0" # 0 = disable
